# Generated by Django 3.1 on 2020-10-13 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictMinorWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256)),
                ('project_name', models.CharField(max_length=256)),
                ('attachment', models.CharField(max_length=256)),
                ('proposer', models.CharField(max_length=256)),
                ('objective', models.TextField()),
                ('desc', models.TextField()),
                ('project_number', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('remarks', models.CharField(max_length=256)),
                ('start_date', models.CharField(max_length=256)),
                ('end_date', models.CharField(max_length=256)),
                ('project_pdf', models.CharField(max_length=2056)),
                ('document_date', models.CharField(max_length=128)),
                ('budget', models.DecimalField(decimal_places=4, max_digits=50)),
                ('audience', models.CharField(max_length=128)),
                ('audience_size', models.CharField(max_length=128)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
