# Generated by Django 3.1 on 2020-10-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_districtminorwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtminorwork',
            name='audience',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='districtminorwork',
            name='audience_size',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
