# Generated by Django 3.1 on 2020-11-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_auto_20201013_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictMinorWorkMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
                ('identifier', models.CharField(max_length=256)),
                ('committee', models.CharField(max_length=256)),
                ('document_no', models.CharField(max_length=256)),
                ('document_date', models.DateField()),
                ('project_pdf', models.CharField(max_length=2056)),
                ('attachment', models.CharField(max_length=256)),
                ('proposer', models.CharField(max_length=256)),
                ('objective', models.TextField()),
                ('audience_all_citizen', models.CharField(max_length=32)),
                ('audience_elderly', models.CharField(max_length=32)),
                ('audience_youth', models.CharField(max_length=32)),
                ('audience_disabled', models.CharField(max_length=32)),
                ('audience_others', models.CharField(max_length=32)),
                ('audience_size', models.CharField(max_length=128, null=True)),
                ('ballpark', models.DecimalField(decimal_places=0, max_digits=50)),
                ('ballpark_text', models.CharField(max_length=128, null=True)),
                ('outline', models.TextField()),
                ('location', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='address',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='audience_size',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='document_date',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='id',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='project_number',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='project_pdf',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='proposer',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='districtminorwork',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='districtminorwork',
            name='identifier',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
