# Generated by Django 3.1 on 2020-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_auto_20201120_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtminorworkmetadata',
            name='id',
        ),
        migrations.AddField(
            model_name='districtminorworkmetadata',
            name='audience_kids',
            field=models.CharField(default='No', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='districtminorworkmetadata',
            name='identifier',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
