# Generated by Django 3.1 on 2020-11-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_auto_20201120_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtminorwork',
            name='metadata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.districtminorworkmetadata'),
        ),
    ]
