# Generated by Django 3.1 on 2020-12-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_communityactivity_communityactivitymetadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityactivity',
            old_name='mpoints',
            new_name='mpoly',
        ),
    ]
