# Generated by Django 3.1 on 2020-12-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_auto_20201223_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtminorworkmetadata',
            name='audience',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='districtminorworkmetadata',
            name='expected_date_format',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='districtminorworkmetadata',
            name='expected_end_date',
            field=models.DateField(default=None,null=True,blank=True),
        ),
        migrations.AddField(
            model_name='districtminorworkmetadata',
            name='expected_start_date',
            field=models.DateField(default=None,null=True,blank=True),
        ),
    ]
