# Generated by Django 3.1 on 2020-12-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_communityactivity_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='audience_size',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
