# Generated by Django 3.1 on 2020-12-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0015_communityactivitymetadata_audience_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='start_date_1',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
