# Generated by Django 3.1 on 2021-01-24 04:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0016_auto_20201224_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=256)),
                ('img', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultModel',
            fields=[
                ('key', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=256)),
                ('project_name', models.CharField(max_length=256)),
                ('committee', models.CharField(max_length=256)),
                ('document_url', models.CharField(max_length=1024)),
                ('start_date', models.DateField()),
                ('audience', models.CharField(max_length=256)),
                ('objective', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=1024)),
                ('record_type', models.CharField(max_length=1024)),
                ('mpoly', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('estimation', models.DecimalField(decimal_places=0, max_digits=50)),
            ],
        ),
    ]
