# Generated by Django 3.1 on 2021-02-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0018_auto_20210228_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='objective',
            field=models.CharField(max_length=2048),
        ),
    ]
