# Generated by Django 3.1 on 2021-03-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0019_auto_20210228_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
