# Generated by Django 3.1 on 2021-03-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0020_communityactivitymetadata_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityactivitymetadata',
            old_name='end_date_type_2',
            new_name='end_date_type_1',
        ),
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='end_date_1',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
