# Generated by Django 3.1 on 2021-03-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0021_auto_20210309_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.communityactivity'),
        ),
    ]
