# Generated by Django 3.1 on 2021-03-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0022_communityactivitymetadata_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='approved',
            field=models.CharField(default=True, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='category',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
