# Generated by Django 3.1 on 2021-03-10 00:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0023_auto_20210309_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
