# Generated by Django 3.1 on 2021-03-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0025_auto_20210310_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='category_text',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='districtminorworkmetadata',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.category'),
        ),
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.category'),
        ),
    ]
