# Generated by Django 3.1 on 2021-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0026_auto_20210310_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
