# Generated by Django 3.1 on 2021-03-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0027_category_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.communityactivitymetadata'),
        ),
        migrations.AddField(
            model_name='districtminorworkmetadata',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.districtminorworkmetadata'),
        ),
    ]
