# Generated by Django 3.1 on 2021-03-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0028_auto_20210313_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='version',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='districtminorworkmetadata',
            name='version',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
