# Generated by Django 3.1 on 2021-03-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0029_auto_20210313_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='stacked_bar_chart_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityactivitymetadata',
            name='stacked_bar_chart_flag',
            field=models.CharField(default='Y', max_length=2),
        ),
    ]
