# Generated by Django 3.1 on 2021-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0031_auto_20210313_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='coorganizer_govt',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='coorganizer_non_govt',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='helping_organization',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='nature',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='organization_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='payee',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='communityactivitymetadata',
            name='project_name',
            field=models.CharField(max_length=512),
        ),
    ]
