# Generated by Django 3.1 on 2021-03-13 16:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0033_auto_20210313_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactivity',
            name='gc',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='districtminorwork',
            name='gc',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(default=None, null=True, srid=4326),
        ),
    ]
