# Generated by Django 3.1 on 2021-03-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0034_auto_20210313_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtminorworkmetadata',
            name='approved',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
